name: fandom_clone
description: FANDOM Mobile Skin clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/img/
